[package]
name = 'suihub'
authors = ["Mo Ashouri <ashourics@gmail.com>"]


[package]
name = 'suihub'
version = '1.0.0'
authors = ["Mohammadreza Ashouri <ashourics@gmail.com>"] 

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "testnet" }

[addresses]
suihub = "0x0"


